name: acapy-bdd-interop-tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false && github.repository == 'hyperledger/aries-cloudagent-python') || (github.event_name != 'pull_request')
    outputs:
      is_release: ${{ steps.check_if_release.outputs.is_release }}
    steps:
      - name: checkout-acapy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # ----------------------------------------------
      #       Install docker compose
      # ----------------------------------------------
      - name: Initialize Docker Compose
        uses: isbang/compose-action@v1.5.1
      - name: Run BDD Interop Tests
        run: |
          # Get AATH 
          git clone https://github.com/hyperledger/aries-agent-test-harness.git
          ls -a
          cd aries-agent-test-harness
          ./manage build -a acapy
          ./manage run -d acapy -t @AcceptanceTest -t ~@wip -t ~@T004-RFC0211 -t ~@DidMethod_orb -t ~@Transport_NoHttpOutbound

