name: acapy-integration-tests

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.draft == false && github.repository == 'jamshale/aries-cloudagent-python') || (github.event_name != 'pull_request')
    steps:
      - name: checkout-acapy
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
        id: setup-poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Run Integration tests
        run: |
          # Build the docker image for testing
          docker build -t acapy-test -f docker/Dockerfile.run .
          cd integration-tests
          poetry install --no-root
          poetry run pytest -m examples
