name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  tests:
    name: Test Python ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: Install the project dependencies
        run: |
          pip install poetry
          poetry install --all-extras
      - name: Tests
        run: |
          poetry run pytest --cov --cov-report xml 2>&1 | tee pytest.log
          PYTEST_EXIT_CODE=${PIPESTATUS[0]}
          if grep -Eq "RuntimeWarning: coroutine .* was never awaited" pytest.log; then
            echo "Failure: Detected unawaited coroutine warning in pytest output."
            exit 1
          fi
          exit $PYTEST_EXIT_CODE
      - name: Save PR number to file
        run: echo ${{ github.event.number }} > PR_NUMBER
      - name: Archive PR number
        uses: actions/upload-artifact@v4
        with:  
          name: PR_NUMBER
          path: PR_NUMBER
      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:  
          name: TEST_COV
          path: ./test-reports/coverage.xml
